version: "3.6"

services:
  # mongo service
  fullstack-ts-mongodb-local:
    image: mongo:latest
    container_name: fullstack-ts-mongodb-local
    ports:
      - 27018:27018
    expose:
      - 27018
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo_net

volumes:
  mongo-data:

networks:
  mongo_net:
    driver: bridge
